### PR TITLE
CommitRef

### PR DESCRIPTION
**Pull request by jairbubbles**

### CODE REVIEW

**Comment by kekyo** [comment]
@jairbubbles Yesterday, I thought it would be appropriate to add `Branch.GetCommitAsync()`, given the results of the discussion in #1. I haven't looked at the details yet, but it reads like it is based on the same idea :)

**Comment by kekyo** [comment]
@jairbubbles I'm going to implement it here, can I take over some of your implementation? (will cherry-pick and modify)

**Comment by jairbubbles** [comment]
Please do!

**Comment by kekyo** [comment]
Merged, thanks!

* The `CommitRef` abstract class is turned to an interface `ICommitReference`.
  * Related hash code `Hash` is hided on `Branch`, `Tag` and `ReflogEntry` except `Commit`. Because it is considered rare that we would want to get a `Hash` from these items. We can avoid getting lost in the selection of member methods (especially the IntelliSense list).
* Added F# interfaces and tests.

**Pull request closed without merging**
