### PR TITLE
Add failing test CacheFileStreamDisposeProperly

### PR DESCRIPTION
**Pull request by trejjam**
Hi, when I start using this library inside a source generator I start hitting issues when I was committing.

I discovered that after a repository is disposed, streams are still locked. I did not find a reason. Here is at least a failing test. If you can navigate me to the issue, it will be really nice.

### CODE REVIEW

**Comment by trejjam** [comment]
I was searching for how is this happening, and so far I did not find the cause. I can ques there is a memory leak.

Why I think so:
I implemented PrimitiveFileStream as a replacement for FileStreamCache. When I create a repository with PrimitiveFileStream CacheFileStreamDisposeProperly pass. This implies that the issue is in FileStreamCache. At the same time, when I create a new repository with FileStreamCache the test also passes. Therefore there is some state that is not properly discarded, and also is static, because it survive new instance creation.

**Comment by kekyo** [comment]
@trejjam Thank you this issue reporting, I researched this problem and found the cause.

When a `CachedStream` was retrieved from the cache and reused, it was accidentally reused in a discarded state, resulting in it losing its timing to be completely discarded by `CloseExact()`.

This part of the implementation was a bit skimpy and the code was difficult to understand due to bad habits caused by OOP inheritance, so I changed the implementation to one using delegation.

The test of the following commit passes without problems in my environment: f18716eb72c6b427fa6da6ace13e56a7f90698c3

I would like to merge this branch with the test code you added, if it is OK there, too.

**Comment by trejjam** [comment]
I tested it, and it seems that it works as expected.
The file is locked for a moment and when it gets out of the cache is properly released.

Thank you for your quick response 🎉

**Comment by kekyo** [comment]
I will be merged!

**Pull request merged**
